### ISSUE TITLE
Could not find any downloads that satisfy the requirement magic

### ISSUE THREAD

**Issue by urbels** [daboross/qxlc#2]
pip install -r requirements.txt
Downloading/unpacking magic (from -r requirements.txt (line 1))
  Could not find any downloads that satisfy the requirement magic (from -r requirements.txt (line 1))
Cleaning up...
No distributions at all found for magic (from -r requirements.txt (line 1))

**Comment by daboross** [comment]
Should be fixed

**Comment by urbels** [comment]
thx
